### ISSUE TITLE
Unable to connect to Google on Android

### ISSUE THREAD

**Issue by Jakub684** [osp54/CloudSave#1]
MINDUSTRY
release build  143

An error has occured
An error occurred while connecting to Google Drive (unable to create directory: /tokens)

**\> IO: 'unable to create directory: /tokens'
FileDataStoreFactory.<init>: 72
GoogleDrive.getCredentials: 171
GoogleDrive.lambda$connect$0: 72
Settings
-$$Lambda$GoogleDrive$7BYnVcQ9hXETpzFF9X3KFXHtJEA.run: 0
Executors$RunnableAdapter.call: 462
FutureTask.run: 266
ThreadPoolExecutor.runWorker: 1167 ThreadPoolExecutor$Worker.run: 641
Thread.run: 929**

**Comment by Jakub684** [comment]
Storage permissions were enabled.

**Comment by osp54** [comment]
I don't seem to have tested on android. Since I had some inconvenience with google, I decided to write my own save server. The server is already ready, but the mod which will interact with the server is still in development.

**Comment by Jakub684** [comment]
Nice, looking forward to the next release.
