### ISSUE TITLE
connect not working

### ISSUE THREAD

**Issue by ItsOnlyMe360** [osp54/CloudSave#2]
when connect is clicked, nothing happens (low fps just on recording, my game runs smooth)

https://user-images.githubusercontent.com/126713125/232349445-364840c6-4b20-4a7e-a918-6d005001f8a9.mp4

**Comment by Shadow-Hunt3r** [comment]
If now I got a similar error, something about not able to make a directory?
Here's a screenshot of the error that I got in detail

[Screenshot_20230615-203813.png](https://github.com/osp54/CloudSave/assets/99599775/6950c06f-a6e7-44aa-a6f5-a8dfeeee72f6)

Edit: instead of making a new directory then couldn't it make a file beside itself in the mods folder, this was on the android release of the game

**Comment by osp54** [comment]
> If now I got a similar error, something about not able to make a directory? Here's a screenshot of the error that I got in detail
> 
> [Screenshot_20230615-203813.png](https://github.com/osp54/CloudSave/assets/99599775/6950c06f-a6e7-44aa-a6f5-a8dfeeee72f6)
> 
> Edit: instead of making a new directory then couldn't it make a file beside itself in the mods folder, this was on the android release of the game

Sorry, but the stable version of the project is in development, and lazily developing, I think by the end of the summer will be ready

**Comment by Shadow-Hunt3r** [comment]
> > If now I got a similar error, something about not able to make a directory? Here's a screenshot of the error that I got in detail
> > 
> > [Screenshot_20230615-203813.png](https://github.com/osp54/CloudSave/assets/99599775/6950c06f-a6e7-44aa-a6f5-a8dfeeee72f6)
> > 
> > Edit: instead of making a new directory then couldn't it make a file beside itself in the mods folder, this was on the android release of the game
> 
> Sorry, but the stable version of the project is in development, and lazily developing, I think by the end of the summer will be ready
> 

Fair enough then, it's understandable that you're busy, also I think that instead of hosting your own server for the saves you could give an option for users to set a folder in their network storage drive to be used of they want to if it were possible of course

**Comment by osp54** [comment]
> > > If now I got a similar error, something about not able to make a directory? Here's a screenshot of the error that I got in detail
> > > [Screenshot_20230615-203813.png](https://github.com/osp54/CloudSave/assets/99599775/6950c06f-a6e7-44aa-a6f5-a8dfeeee72f6)
> > > Edit: instead of making a new directory then couldn't it make a file beside itself in the mods folder, this was on the android release of the game
> > 
> > 
> > Sorry, but the stable version of the project is in development, and lazily developing, I think by the end of the summer will be ready
> 
> Fair enough then, it's understandable that you're busy, also I think that instead of hosting your own server for the saves you could give an option for users to set a folder in their network storage drive to be used of they want to if it were possible of course

The save server will be open-source, and maybe there will be documentation on how to run it, so that's it.

**Comment by ItsOnlyMe360** [comment]
https://github.com/osp54/CloudSave/assets/126713125/a93cd8bc-3bc7-44ce-b580-9a9948faf616

As the developer is creating a new update using his own Server, i think the issue will be gone.
